import time
timestamp=time.strftime("%a, %d %b %Y, %H:%M:%S")
print(timestamp)
day=time.strftime("%a")
print("day: ",day)
date=time.strftime("%d")
print('date: ',date)
month=time.strftime("%b")
print("month: ",month)
year=time.strftime("%Y")
print("year: ",year)
hours=time.strftime("%H")
print("hour: ",hours,"hr")
minute=time.strftime("%M")
print("minute: ",minute,"min")
seconds=time.strftime("%S")
print("socond: ",seconds,"sec")
